# This file is part of tad-mctc.
#
# SPDX-Identifier: Apache-2.0
# Copyright (C) 2024 Grimme Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""
Data: mstore
============

Python mirror of every dataset and record in
https://github.com/grimme-lab/mstore (upstream ``main``, not the older
v0.3.0 tag some sibling Grimme-group repositories still pin), generated by
``tools/mstore/convert.py``. One module per dataset, matching mstore's own
Fortran file boundaries, each keyed by mstore's own bare record ids rather
than any locally-invented naming. Records mirror geometry and, where
mstore's source subroutine sets them, lattice, charge and uhf; see each
generated module's docstring for its exact source file and commit.

This package only supplies data; look records up through
:func:`tad_mctc.data.structures.get_structure`.
"""

from __future__ import annotations

from torch import Tensor

from .amino20x4 import amino20x4
from .amylose import amylose
from .but14diol import but14diol
from .f_block import f_block
from .heavy28 import heavy28
from .ice10 import ice10
from .il16 import il16
from .mb16_43 import mb16_43
from .polyalanine import polyalanine
from .rc21 import rc21
from .upu23 import upu23
from .x23 import x23

__all__ = [
    "amino20x4",
    "amylose",
    "but14diol",
    "f_block",
    "heavy28",
    "ice10",
    "il16",
    "mb16_43",
    "polyalanine",
    "rc21",
    "upu23",
    "x23",
    "datasets",
]


datasets: dict[str, dict[str, dict[str, Tensor]]] = {
    "amino20x4": amino20x4,
    "amylose": amylose,
    "but14diol": but14diol,
    "f_block": f_block,
    "heavy28": heavy28,
    "ice10": ice10,
    "il16": il16,
    "mb16_43": mb16_43,
    "polyalanine": polyalanine,
    "rc21": rc21,
    "upu23": upu23,
    "x23": x23,
}
