# This file is part of tad-mctc.
#
# SPDX-Identifier: Apache-2.0
# Copyright (C) 2024 Grimme Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""
Data: mstore
============

Python mirror of every dataset and record in
https://github.com/grimme-lab/mstore (upstream ``main``, not the older
v0.3.0 tag some sibling Grimme-group repositories still pin), generated by
``tools/mstore/convert.py``. One module per dataset, matching mstore's own
Fortran file boundaries, each keyed by mstore's own bare record ids rather
than any locally-invented naming. Records mirror geometry and, where
mstore's source subroutine sets them, lattice, charge and uhf; see each
generated module's docstring for its exact source file and commit.

:func:`get_structure` is the Pythonic analogue of mstore's own
``get_structure(mol, collection, record)``.
"""

from __future__ import annotations

import torch
from torch import Tensor

from ....io.structure import Structure
from .amino20x4 import amino20x4
from .amylose import amylose
from .but14diol import but14diol
from .f_block import f_block
from .heavy28 import heavy28
from .ice10 import ice10
from .il16 import il16
from .mb16_43 import mb16_43
from .polyalanine import polyalanine
from .rc21 import rc21
from .upu23 import upu23
from .x23 import x23

__all__ = [
    "amino20x4",
    "amylose",
    "but14diol",
    "f_block",
    "heavy28",
    "ice10",
    "il16",
    "mb16_43",
    "polyalanine",
    "rc21",
    "upu23",
    "x23",
    "datasets",
    "get_structure",
    "list_collections",
    "list_records",
]


datasets: dict[str, dict[str, dict[str, Tensor]]] = {
    "amino20x4": amino20x4,
    "amylose": amylose,
    "but14diol": but14diol,
    "f_block": f_block,
    "heavy28": heavy28,
    "ice10": ice10,
    "il16": il16,
    "mb16_43": mb16_43,
    "polyalanine": polyalanine,
    "rc21": rc21,
    "upu23": upu23,
    "x23": x23,
}


def get_structure(
    collection: str,
    record: str,
    device: torch.device | None = None,
    dtype: torch.dtype | None = None,
) -> Structure:
    """
    Look up one structure by dataset and record id, mirroring mstore's own
    ``get_structure(mol, collection, record)``.

    Unrelated to :func:`tad_mctc.data.structures.glu_ala.get_structure`,
    which shares this name but not its shape (one positional argument,
    not two) or its data source -- the two are never meant to be
    interchangeable; only the module path tells them apart.

    Parameters
    ----------
    collection : str
        Dataset name, one of :data:`datasets`' keys (e.g. ``"x23"``).
    record : str
        Record id within that dataset, mstore's own bare spelling (e.g.
        ``"acetic"``, not any locally-invented alias).
    device : torch.device | None, optional
        Device to move the structure to. ``None`` keeps the cached
        dataset's device. Passing a ``DD`` via ``**dd`` works, since its
        keys match these parameter names.
    dtype : torch.dtype | None, optional
        Floating dtype for the structure's floating-point fields. ``None``
        keeps the cached dataset's dtype.

    Returns
    -------
    Structure
        The requested structure.

    Raises
    ------
    KeyError
        If ``collection`` or ``record`` is not found, listing the valid
        options for whichever lookup failed.
    """
    try:
        collection_dict = datasets[collection]
    except KeyError:
        raise KeyError(
            f"Unknown mstore collection '{collection}'. Available: "
            f"{sorted(datasets)}"
        ) from None

    try:
        record_dict = collection_dict[record]
    except KeyError:
        raise KeyError(
            f"Unknown record '{record}' in mstore collection "
            f"'{collection}'. Available: {sorted(collection_dict)}"
        ) from None

    return Structure(**record_dict).to(device=device, dtype=dtype)


def list_collections() -> list[str]:
    """
    List every mirrored dataset name, mirroring mstore's own
    ``list_collections``.

    Returns
    -------
    list[str]
        The keys of :data:`datasets`.
    """
    return list(datasets)


def list_records(collection: str) -> list[str]:
    """
    List every record id in one dataset, mirroring mstore's own
    ``list_records``.

    Parameters
    ----------
    collection : str
        Dataset name, one of :data:`datasets`' keys (e.g. ``"x23"``).

    Returns
    -------
    list[str]
        The record ids in that dataset.

    Raises
    ------
    KeyError
        If ``collection`` is not found, listing the valid collections.
    """
    try:
        collection_dict = datasets[collection]
    except KeyError:
        raise KeyError(
            f"Unknown mstore collection '{collection}'. Available: "
            f"{sorted(datasets)}"
        ) from None

    return list(collection_dict)
